

const CONSTANTS={}
CONSTANTS.USERNAME = 'Username';
CONSTANTS.PASSWORD = 'Password';
CONSTANTS.SECURE_LOGIN = 'Secure Login';
CONSTANTS.EMAIL = 'Email';
CONSTANTS.USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";
CONSTANTS.USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
CONSTANTS.USER_LOGIN_FAIL="USER_LOGIN_FAIL";

export default CONSTANTS
